#!/usr/bin/env python3
"""Build compact 1-bit V5F boot-screen assets from official PNG sources.

The firmware renders both marks with one palette colour on a white L8
framebuffer.  Keeping only coverage bits makes the generated data small and
avoids shipping a PNG decoder in V5F.
"""

from __future__ import print_function

import argparse
from pathlib import Path

from PIL import Image


DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 480
COMPETITION_BLUE = (31, 78, 121)
LOGO_HEIGHT = 184
SLOGAN_WIDTH = 724
LOGO_Y = 70
SLOGAN_Y = 296


def _resample_lanczos():
    resampling = getattr(Image, "Resampling", None)
    if resampling is not None:
        return resampling.LANCZOS
    return Image.LANCZOS


def _blue_mask(image):
    """Select only the blue tree mark and reject the grey caption."""
    rgb = image.convert("RGB")
    mask = Image.new("L", rgb.size, 0)
    source = rgb.load()
    destination = mask.load()
    for y in range(rgb.height):
        for x in range(rgb.width):
            red, green, blue = source[x, y]
            chroma = blue - max(red, green)
            if chroma > 4:
                destination[x, y] = min(255, chroma * 4)
    return mask


def _crop_nonempty(mask):
    bbox = mask.getbbox()
    if bbox is None:
        raise ValueError("source image contains no drawable pixels")
    return mask.crop(bbox)


def _resize_to_height(mask, height):
    width = max(1, int(round(mask.width * float(height) / mask.height)))
    return mask.resize((width, height), _resample_lanczos())


def _resize_to_width(mask, width):
    height = max(1, int(round(mask.height * float(width) / mask.width)))
    return mask.resize((width, height), _resample_lanczos())


def _threshold(mask, cutoff=72):
    return mask.point(lambda value: 255 if value >= cutoff else 0, mode="1")


def _pack_rows(mask):
    width, height = mask.size
    stride = (width + 7) // 8
    packed = bytearray(stride * height)
    pixels = mask.load()
    for y in range(height):
        for x in range(width):
            if pixels[x, y]:
                packed[(y * stride) + (x // 8)] |= 0x80 >> (x & 7)
    return bytes(packed), stride


def _format_bytes(data):
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + ", ".join("0x%02Xu" % value for value in chunk) + ",")
    return "\n".join(lines)


def _write_header(path, logo, slogan):
    logo_data, logo_stride = _pack_rows(logo)
    slogan_data, slogan_stride = _pack_rows(slogan)
    content = """/* Generated by tools/make_competition_ui_assets.py. */
#ifndef V5F_COMPETITION_ASSETS_H
#define V5F_COMPETITION_ASSETS_H

#include <stdint.h>

#define V5F_COMPETITION_LOGO_WIDTH       {logo_width}u
#define V5F_COMPETITION_LOGO_HEIGHT      {logo_height}u
#define V5F_COMPETITION_LOGO_STRIDE      {logo_stride}u
#define V5F_COMPETITION_SLOGAN_WIDTH     {slogan_width}u
#define V5F_COMPETITION_SLOGAN_HEIGHT    {slogan_height}u
#define V5F_COMPETITION_SLOGAN_STRIDE    {slogan_stride}u

static const uint8_t s_v5f_competition_logo_bits[]
    __attribute__((section(".image_rodata"), aligned(4))) = {{
{logo_data}
}};

static const uint8_t s_v5f_competition_slogan_bits[]
    __attribute__((section(".image_rodata"), aligned(4))) = {{
{slogan_data}
}};

#endif /* V5F_COMPETITION_ASSETS_H */
""".format(
        logo_width=logo.width,
        logo_height=logo.height,
        logo_stride=logo_stride,
        slogan_width=slogan.width,
        slogan_height=slogan.height,
        slogan_stride=slogan_stride,
        logo_data=_format_bytes(logo_data),
        slogan_data=_format_bytes(slogan_data),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as output:
        output.write(content)


def _write_preview(path, logo, slogan):
    preview = Image.new("RGB", (DISPLAY_WIDTH, DISPLAY_HEIGHT), (255, 255, 255))
    logo_x = (DISPLAY_WIDTH - logo.width) // 2
    slogan_x = (DISPLAY_WIDTH - slogan.width) // 2
    logo_y = LOGO_Y
    slogan_y = SLOGAN_Y
    blue_layer = Image.new("RGB", preview.size, COMPETITION_BLUE)
    logo_alpha = Image.new("L", preview.size, 0)
    slogan_alpha = Image.new("L", preview.size, 0)
    logo_alpha.paste(logo.convert("L"), (logo_x, logo_y))
    slogan_alpha.paste(slogan.convert("L"), (slogan_x, slogan_y))
    preview.paste(blue_layer, mask=logo_alpha)
    preview.paste(blue_layer, mask=slogan_alpha)
    path.parent.mkdir(parents=True, exist_ok=True)
    preview.save(path)


def build_assets(logo_path, slogan_path, header_path, preview_path):
    logo_source = Image.open(str(logo_path))
    logo_mask = _threshold(
        _resize_to_height(_crop_nonempty(_blue_mask(logo_source)), LOGO_HEIGHT)
    )

    slogan_source = Image.open(str(slogan_path)).convert("RGBA")
    slogan_mask = _threshold(
        _resize_to_width(
            _crop_nonempty(slogan_source.getchannel("A")),
            SLOGAN_WIDTH,
        ),
        cutoff=40,
    )

    if LOGO_Y + logo_mask.height >= SLOGAN_Y:
        raise ValueError("logo overlaps slogan")
    if SLOGAN_Y + slogan_mask.height > DISPLAY_HEIGHT:
        raise ValueError("slogan does not fit 800x480 display")

    _write_header(header_path, logo_mask, slogan_mask)
    _write_preview(preview_path, logo_mask, slogan_mask)
    print("logo: %ux%u" % logo_mask.size)
    print("slogan: %ux%u" % slogan_mask.size)
    print("header: %s" % header_path)
    print("preview: %s" % preview_path)


def main():
    project = Path(__file__).resolve().parents[1]
    source = project / "assets" / "competition" / "source"
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--logo",
        type=Path,
        default=source / "socchina-logo-official.png",
    )
    parser.add_argument(
        "--slogan",
        type=Path,
        default=source / "2026-slogan-official.png",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=project / "applications" / "v5f_competition_assets.h",
    )
    parser.add_argument(
        "--preview",
        type=Path,
        default=(
            project
            / "assets"
            / "competition"
            / "generated"
            / "v5f_competition_boot_preview.png"
        ),
    )
    args = parser.parse_args()
    build_assets(args.logo, args.slogan, args.header, args.preview)


if __name__ == "__main__":
    main()
