#ifndef H4V1_FLASH_POSTPASS_STAGE4_H
#define H4V1_FLASH_POSTPASS_STAGE4_H

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    H4V1_FLASH_POSTPASS_STAGE4_OK = 0,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_DMA_BUSY = -1,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_PROBE = -2,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_MARKER = -3,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_SPI = -4,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_READY = -5,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_ECC = -6,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_DMA = -7,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_DMA_QUIESCE = -8,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_DATA = -9,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_UNSTABLE = -10,
    H4V1_FLASH_POSTPASS_STAGE4_ERR_RESTORE = -11
};

int h4v1_flash_postpass_stage4_run(void);

#ifdef __cplusplus
}
#endif

#endif
