#ifndef H4V1_FLASH_POSTPASS_STAGE5_H
#define H4V1_FLASH_POSTPASS_STAGE5_H

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    H4V1_FLASH_POSTPASS_STAGE5_OK = 0,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_DMA_BUSY = -1,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_PROBE = -2,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_FEATURE = -3,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_MARKER = -4,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_SPI = -5,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_READY = -6,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_ECC = -7,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_DMA = -8,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_DMA_QUIESCE = -9,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_ERASE = -10,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_PROGRAM = -11,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_VERIFY = -12,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_CLEANUP = -13,
    H4V1_FLASH_POSTPASS_STAGE5_ERR_ILLEGAL_COMMAND = -14
};

int h4v1_flash_postpass_stage5_run(void);

#ifdef __cplusplus
}
#endif

#endif
