#ifndef H4V1_FLASH_INSTALLER_STAGE6_H
#define H4V1_FLASH_INSTALLER_STAGE6_H

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    H4V1_FLASH_INSTALLER_STAGE6_OK = 0,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_DMA_BUSY = -1,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_PROBE = -2,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_FEATURE = -3,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_MARKER = -4,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_SPI = -5,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_READY = -6,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_ECC = -7,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_DMA = -8,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_DMA_QUIESCE = -9,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_ERASE = -10,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_PROGRAM = -11,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_VERIFY = -12,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_CLEANUP = -13,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_ILLEGAL_COMMAND = -14,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_CAPACITY = -15,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_CONTRACT = -16,
    H4V1_FLASH_INSTALLER_STAGE6_ERR_MANIFEST = -17
};

int h4v1_flash_installer_stage6_run(void);

#ifdef __cplusplus
}
#endif

#endif


