#ifndef CH585_BOARD_CONFIG_H
#define CH585_BOARD_CONFIG_H

/* Board model is independent of the left/right half role. */
#define CH585_BOARD_MODEL_OLD 0U
#define CH585_BOARD_MODEL_NEW 1U

#ifndef CH585_BOARD_MODEL
#define CH585_BOARD_MODEL CH585_BOARD_MODEL_NEW
#endif

#if (CH585_BOARD_MODEL != CH585_BOARD_MODEL_OLD) && \
    (CH585_BOARD_MODEL != CH585_BOARD_MODEL_NEW)
#error Unsupported CH585_BOARD_MODEL.
#endif

#if CH585_BOARD_MODEL == CH585_BOARD_MODEL_NEW
#define CH585_BOARD_MODEL_NAME "NEW"
#define CH585_BOARD_HAS_WIRELESS_MODE_SWITCH 1U
#else
#define CH585_BOARD_MODEL_NAME "OLD"
#define CH585_BOARD_HAS_WIRELESS_MODE_SWITCH 0U
#endif

#endif /* CH585_BOARD_CONFIG_H */
