import io
import os
import unittest


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
CH585_MAKEFILE = os.path.join(ROOT, "hw_tests", "ch585", "Makefile")
CH585_COMMON_H = os.path.join(ROOT, "hw_tests", "ch585", "src", "ch585_common.h")
CH585_TEST = os.path.join(ROOT, "hw_tests", "ch585", "src", "ch585_spi0_speed_slave.c")
CH585_SPI0_LINK_DRIVER = os.path.join(ROOT, "firmware", "ch585", "drivers", "ch585_spi0_slave_link.c")
H417_MAKEFILE = os.path.join(ROOT, "hw_tests", "h417", "Makefile")
H417_V5F_MAKEFILE = os.path.join(ROOT, "firmware", "h417", "v5f_rtthread", "Makefile")
H417_V5F_H = os.path.join(ROOT, "hw_tests", "h417", "passed", "v5f_rtthread", "include", "v5f_hw_test.h")
H417_V5F_TEST = os.path.join(ROOT, "hw_tests", "h417", "passed", "v5f_rtthread", "src", "v5f_hw_test.c")
PROTO_H = os.path.join(ROOT, "hw_tests", "common", "ch585_h417_spi_speed_proto.h")


def read_text(path):
    with io.open(path, "r", encoding="utf-8") as handle:
        return handle.read()


class Ch585H417SpiSpeedHwTestPolicy(unittest.TestCase):
    def test_shared_protocol_is_hw_test_owned(self):
        proto = read_text(PROTO_H)

        self.assertIn("CH585_H417_SPI_SPEED_FRAME_BYTES 192U", proto)
        self.assertIn("CH585_H417_SPI_SPEED_TRANSFER_BYTES 193U", proto)
        self.assertIn("CH585_H417_SPI_SPEED_FRAME_OFF", proto)
        self.assertIn("CH585_H417_SPI_SPEED_MAGIC", proto)
        self.assertIn("CH585_H417_SPI_SPEED_READY_BYTE", proto)
        self.assertIn("CH585_H417_SPI_SPEED_PAYLOAD_OFF", proto)
        self.assertIn("ch585_h417_spi_speed_fixed_byte", proto)
        self.assertIn("ch585_h417_spi_speed_payload_byte", proto)
        self.assertIn("ch585_h417_spi_speed_crc16", proto)
        self.assertNotIn("ADC", proto)
        self.assertNotIn("USBHS", proto)

    def test_ch585_spi0_slave_hw_test_entry(self):
        makefile = read_text(CH585_MAKEFILE)
        common_h = read_text(CH585_COMMON_H)
        source = read_text(CH585_TEST)
        driver = read_text(CH585_SPI0_LINK_DRIVER)

        self.assertIn("ch585_spi0_speed_slave", makefile)
        self.assertIn("CH58x_spi0.c", makefile)
        self.assertIn("ch585_spi0_slave_link.c", makefile)
        self.assertIn("void ch585_spi0_speed_slave_run(void);", common_h)
        self.assertIn("#include \"ch585_spi0_slave_link.h\"", source)
        self.assertIn("#include \"ch585_h417_spi_speed_proto.h\"", source)
        self.assertIn("SPI0_SlaveInit();", driver)
        self.assertIn("ch585_spi0_speed_init_fixed_transfer", source)
        self.assertIn("CH585_H417_SPI_SPEED_READY_BYTE", source)
        self.assertIn("CH585_H417_SPI_SPEED_TRANSFER_BYTES", source)
        self.assertNotIn("ch585_spi0_speed_send_ready", source)
        self.assertIn("ch585_h417_spi_speed_fixed_byte", source)
        self.assertNotIn("ch585_h417_spi_speed_payload_byte", source)
        self.assertIn("ch585_spi0_slave_link_serve_tx_frame", source)
        self.assertIn("s_ch585_spi0_slave_link_aborts", driver)
        self.assertIn("saw_select", driver)
        self.assertIn("R8_SPI0_BUFFER", driver)
        self.assertIn("RB_SPI_IF_FIFO_OV", driver)
        self.assertIn("SetFirstData", driver)
        self.assertIn("PA12_CS_PA13_SCK_PA14_MOSI_PA15_MISO", source)
        self.assertIn("ch585_log_str", source)
        self.assertNotIn("USBHS", source)
        self.assertNotIn("ads7948", source.lower())

    def test_h417_v5f_spi1_master_hw_test_entry(self):
        h417_makefile = read_text(H417_MAKEFILE)
        v5f_makefile = read_text(H417_V5F_MAKEFILE)
        header = read_text(H417_V5F_H)
        source = read_text(H417_V5F_TEST)

        self.assertIn("SPI_SOURCE ?= left", h417_makefile)
        self.assertIn("h417_v5f_ch585_spi_speed", h417_makefile)
        self.assertIn("APP_V5F_HW_TEST_MODE := ch585_spi_speed", h417_makefile)
        self.assertIn("APP_V5F_HW_TEST_USB_CDC := 1", h417_makefile)
        self.assertIn("APP_CH585_SPI_SPEED_SOURCE_LEFT=1", h417_makefile)
        self.assertIn("APP_CH585_SPI_SPEED_SOURCE_RIGHT=1", h417_makefile)
        self.assertIn("ch585_spi_speed", v5f_makefile)
        self.assertIn("APP_V5F_HW_TEST_CH585_SPI_SPEED", header)
        self.assertIn("#include \"ch585_h417_spi_speed_proto.h\"", source)
        self.assertIn("GPIO_PinAFConfig(GPIOB, GPIO_PinSource3, GPIO_AF5)", source)
        self.assertIn("GPIO_PinAFConfig(GPIOB, GPIO_PinSource5, GPIO_AF5)", source)
        self.assertIn("GPIO_PinAFConfig(GPIOB, GPIO_PinSource4, GPIO_AF5)", source)
        self.assertIn("left/U2 CS=PF2 other=PD9", source)
        self.assertIn("right/U3 CS=PD9 other=PF2", source)
        self.assertIn("CH585_H417_SPI_SPEED_TRANSFER_BYTES", source)
        self.assertNotIn("ch585_spi_speed_poll_ready", source)
        self.assertIn("CH585_H417_SPI_SPEED_READY_BYTE", source)
        self.assertIn("bad_ready", source)
        self.assertIn("bad_fixed", source)
        self.assertIn("CH585_SPI_SPEED_MAX_ATTEMPTS_PER_RATE", source)
        self.assertIn("CH585_SPI_SPEED_SYNC_RETRY_CYCLES", source)
        self.assertIn("attempts=", source)
        self.assertIn("first_bad_off", source)
        self.assertIn("ch585_spi_speed_validate_fixed_transfer", source)
        self.assertIn("ch585_h417_spi_speed_fixed_byte", source)
        self.assertNotIn("ch585_h417_spi_speed_payload_byte", source)
        self.assertIn("\"div8\"", source)
        self.assertIn("\"div4\"", source)
        self.assertIn("\"div2\"", source)
        self.assertIn("\"div4-cpha2\"", source)
        self.assertIn("\"div2-cpha2\"", source)
        self.assertIn("\"div8-hsrx2\"", source)
        self.assertIn("\"div4-hsrx1-cpha2\"", source)
        self.assertIn("first_bad=", source)
        self.assertIn("DIV2_DIAG", source)
        self.assertIn("ch585_spi_speed_is_div2", source)
        self.assertIn("div2_samples", source)
        self.assertIn("div2_rx0_and", source)
        self.assertIn("rx0_and=", source)
        self.assertIn("exp=", source)
        self.assertIn("s0=", source)
        self.assertIn("ch585_spi_speed_find_rate", source)
        self.assertIn("ch585_spi_speed_trim_command", source)
        self.assertIn("ch585_spi_speed_handle_command", source)
        self.assertIn("ch585_spi_speed_poll_command", source)
        self.assertIn("ch32h417_usb_cdc_read_line", source)
        self.assertIn("SPI_CMD", source)
        self.assertIn("'\\r'", source)
        self.assertIn("'\\n'", source)
        self.assertIn("\"rate \"", source)
        self.assertIn("\"once \"", source)
        self.assertIn("\"hf\"", source)
        self.assertIn("\"oncehf\"", source)
        self.assertIn("ch585_spi_speed_run_high_frequency", source)
        self.assertIn("\"auto\"", source)
        self.assertIn("\"stop\"", source)
        self.assertIn("\"help\"", source)
        self.assertNotIn("\"div256\"", source)
        self.assertNotIn("\"div128\"", source)
        self.assertNotIn("\"div64\"", source)
        self.assertNotIn("\"div32\"", source)
        self.assertNotIn("\"div16\"", source)
        self.assertIn("ch32h417_usb_cdc_write", source)
        self.assertIn("SPI_RATE", source)
        self.assertIn("best_khz", source)
        self.assertNotIn("CH585_SPI_SPEED_FRAME_GAP_CYCLES 100000U", source)
        self.assertNotIn("UART8", source)


if __name__ == "__main__":
    unittest.main()
